apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplier-net-ca
  namespace: supplier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplier-net-ca
  chart:
    git: https://github.com/weihong-ou/blockchain-automation-framework.git
    ref: mvp1.0
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: supplier-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: supplier-admin 
  
    storage:
      storageclassname: suppliersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://vault.wei-baf:8200
      authpath: devsupplier-net-auth
      secretcert: secret/crypto/peerOrganizations/supplier-net/ca?ca.supplier-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/supplier-net/ca?supplier-net-CA.key
      secretadminpass: secret/credentials/supplier-net/ca/supplier?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
      external_url_suffix: baf-test.info
